---
- name: build server configuring
  hosts: builder
  become: yes

  roles: 
    - provisioning
    - building

- name: prod server configuring
  hosts: prod
  become: yes

  roles: 
    - provisioning
    - launching   